name: Generate QR code contact card
on:
  workflow_dispatch:
    inputs:
      token:
        description: 'GitHub Personal Access Token'
        required: true
        default: ${{ secrets.GITHUB_TOKEN }}
      COMMIT_MESSAGE:
        required: false
        description: "Git commit message"
        default: "Updated with wordclouds action"
jobs:
  qr:
    name: Setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/qr_requirements.txt
    - name: Generate QR code
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python3 scripts/qr.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ${{ github.event.inputs.COMMIT_MESSAGE }}

