name: WakaTime Stats in README

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PUSH_BRANCH_NAME: main
          SECTION_NAME: My Recent Coding Stats
          SHOW_UPDATED_DATE: True
          SHOW_LINES_OF_CODE: True
          SHOW_TOTAL_CODE_TIME: True
          SHOW_PROFILE_VIEWS: True
          SHOW_COMMIT: True
          SHOW_DAYS_OF_WEEK: True
          SHOW_LANGUAGE: True
          SHOW_OS: True
          SHOW_PROJECTS: True
          SHOW_TIMEZONE: False
          SHOW_EDITORS: False
          SHOW_LANGUAGE_PER_REPO: True
          SHOW_SHORT_INFO: True
          SHOW_LOC_CHART: True
          IGNORED_REPOS: "explorations-in-envy-free-allocations"
